### ISSUE TITLE
[Feature Request] Support for USDT-ERC20?

### ISSUE THREAD

**Issue by reduxionist** [vsys-host/shkeeper.io#10]
Do you have any plans to provide support for USDT-ERC20? Thanks!

**Comment by vsyshost** [comment]
@reduxionist 
Yes 😇

We are currently working on publishing USDT-TRC20 and USDC-TRC20. 
(will be available for free at SHKeeper open-source version)

And after that, we have plans to provide support for USDT-ERC20 and USDC-ERC20.
(will be available at SHKeeper paid version)

**Comment by Jobians** [comment]
@vsyshost have you added TRON, USDT-TRC20 and USDC-TRC20

**Comment by vsyshost** [comment]
> @vsyshost have you added TRON, USDT-TRC20 and USDC-TRC20

We are currently working on the ERC20 implementation for the paid SHKeeper version.

We are also going to make an update and put the TRON, USDT-TRC20 and USDC-TRC20 in the public version in the nearest 4 weeks.

**Comment by Jobians** [comment]
Why you close?

Have you added it
