### ISSUE TITLE
Server Full Nodes

### ISSUE THREAD

**Issue by mvclaudianobj** [vsys-host/shkeeper.io#11]
I have a doubt when configuring the nodes. For BTC, the local full node worked normally, but for the last update of the code in ethereum and tron ​​network, will I have to install fullnode too? Because the parameter seems to allow me to use an external api node... is it possible? can you provide me with an example of .env with the parameters to run the project?

**Comment by vsyshost** [comment]
@mvclaudianobj 

You can use our node for TRON.
But you need to keep your node for Ethereum. Also, for BTC, it is pruned node.

Instead .env, we can provide you with the following:
https://github.com/vsys-host/helm-charts/tree/gh-pages
