### ISSUE TITLE
Idea: integration TRON Lite FullNode

### ISSUE THREAD

**Issue by bulhiCzar** [vsys-host/shkeeper.io#18]
### Reason:
reducing the waiting time for synchronization of the entire blockchain
the jump rate of the full node is 4mbps. and when it is fully downloaded, it will take too much time (or you can make a setup for shkeeper-tron so that you can specify the IP address to another node and follow the node)
this applies to ETH

### Description:
this node provides access to all new blocks, but did not provide access to the history. but we don't need the whole story on how much according to the current logic our addresses in the TRON network are being created at the present moment. and we do not have the ability to download the following addresses

### sources:
https://tronprotocol.github.io/documentation-en/developers/litefullnode/

**Comment by bulhiCzar** [comment]
Yes, if you don't mind
I would like to get information on how to configure values.yaml for Lite FullТode for TRON and ETH

I tried to set it up myself but failed

**Comment by bulhiCzar** [comment]
I did everything as you indicated. even the transactions that I made this week have already been displayed. but the wallet is still in the process of syncing and constantly downloads something over the network

is this normal, will it continue like this?
Sync In Progress (51028546 blocks behind)

it is not at all clear why he writes that (51028546 blocks behind) when the current block is 50882219

**Comment by dmytro-samoylenko** [comment]
Hi,

Perhaps tron wallet last seen block was set to 0 and now it catches up. You may check it with:

```
# sqlite3 /var/lib/rancher/k3s/storage/pvc-65d64be9-b08f-4815-9afa-a02efdcc6ab9_shkeeper_tron-shkeeper-data/database.db 'select * from settings'
last_seen_block_num|50893163
```

If it is too far in the past you may adjust it by running:

```
# sqlite3 /var/lib/rancher/k3s/storage/pvc-65d64be9-b08f-4815-9afa-a02efdcc6ab9_shkeeper_tron-shkeeper-data/database.db 'update settings set value="50893163" where name="last_seen_block_num"'
```

50893163 is a latest block seen by my wallet.

**Comment by bulhiCzar** [comment]
I got this result
```
last_seen_block_num|94361
current_server_id|0
```
this means that now the wallet is located on 94361 blocks, which was many years ago. even though I downloaded LiteFullNode?

and that means I need to install the right block from which I want to start syncing. and will it work?

**Comment by dmytro-samoylenko** [comment]
Hello,

On the first start the wallet receives last block from fullnode server and scans blockchain starting from received block number.

You may replace block number in the db using mentioned command, make sure you stop tron-shkeeper before adjusting the block by running `kubectl -n shkeeper scale --replicas=0 deploy tron-shkeeper` and then start it again with `kubectl -n shkeeper scale --replicas=1 deploy tron-shkeeper`.
