### ISSUE TITLE
callback not being called for DOGE

### ISSUE THREAD

**Issue by petabyt** [vsys-host/shkeeper.io#21]
Hi, I set up this and am running shkeeper with gunicorn. I'm connected to my local wallet, and everything seems to work. I created a payment request, and send 2 dogecoins over. 10 minutes later, and it hasn't done anything. In dogecoin-cli, I can see the transaction has completed, but shkeeper doesn't detect it.

I'm at the latest commit.

Also tried:  
```
$ flask callback list
No unconfirmed transactions found!
```

**Comment by dmytro-samoylenko** [comment]
Hello,

I'm not sure what you mean by local wallet. If you are using dogecoind shipped with shkeeper then check its logs, there must be something along these lines:

```
stdout F <DATE> <TIME> AddToWallet <TXID>  new
stderr F   % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
stderr F                                  Dload  Upload   Total   Spent    Left  Speed
100    21  100    21    0     0   1524      0 --:--:-- --:--:-- --:--:--  1615263346Z stderr F
stdout F {"status":"success"}
```

This output is generated by [walletnotify.sh](https://github.com/vsys-host/helm-charts/blob/main/docker/dogecoind/walletnotify.sh) script which notifies shkeeper about a new transaction and `{"status":"success"}` is a response from shkeeper.

If you are using a custom dogecoin image, make sure you running it with `-walletnotify` and correct `$SHKEEPER_BACKEND_KEY`. Here is how we build our dogecoind image: https://github.com/vsys-host/helm-charts/blob/main/docker/dogecoind/Dockerfile
