### ISSUE TITLE
how to set up this tool without using docker?

### ISSUE THREAD

**Issue by seetimee** [vsys-host/shkeeper.io#22]
I just wanna deploy it on win10

**Comment by bulhiCzar** [comment]
its not real

**Comment by seetimee** [comment]
I have a centos server,but deploy kubernetes took a lot of time,It's hard for a rookie

**Comment by bulhiCzar** [comment]
unfortunately kubernetes is the only way to deploy the application

**Comment by seetimee** [comment]
> unfortunately kubernetes is the only way to deploy the application

Thanks a lot for your reply,bro

**Comment by dmytro-samoylenko** [comment]
Hello,

> I have a centos server,but deploy kubernetes took a lot of time,It's hard for a rookie

Its not hard at all to setup lightweight kubernetes distro (I recommend k3s) on a fresh VPS. Here is an example how to setup k3s and shkeeper on Ubuntu 22 VPS:

```
curl -sfL https://get.k3s.io | sh -
mkdir /root/.kube && ln -s /etc/rancher/k3s/k3s.yaml /root/.kube/config
curl https://raw.githubusercontent.com/helm/helm/main/scripts/get-helm-3 | bash
helm repo add vsys-host https://vsys-host.github.io/helm-charts
helm install my-shkeeper vsys-host/shkeeper
```

After all pods are deployed, open http://<ip>:5000/

If you interested in installation and integration help please check our solution: https://vsys.host/shkeeper

**Comment by seetimee** [comment]
> Hello,
> 
> > I have a centos server,but deploy kubernetes took a lot of time,It's hard for a rookie
> 
> Its not hard at all to setup lightweight kubernetes distro (I recommend k3s) on a fresh VPS. Here is an example how to setup k3s and shkeeper on Ubuntu 22 VPS:
> 
> ```
> curl -sfL https://get.k3s.io | sh -
> mkdir /root/.kube && ln -s /etc/rancher/k3s/k3s.yaml /root/.kube/config
> curl https://raw.githubusercontent.com/helm/helm/main/scripts/get-helm-3 | bash
> helm repo add vsys-host https://vsys-host.github.io/helm-charts
> helm install my-shkeeper vsys-host/shkeeper
> ```
> 
> After all pods are deployed, open http://:5000/
> 
> If you interested in installation and integration help please check our solution: https://vsys.host/shkeeper

I worked.Thanks for your suggestion.
