### ISSUE TITLE
Idea: TRON delegation of energy to payment_address

### ISSUE THREAD

**Issue by bulhiCzar** [vsys-host/shkeeper.io#24]
the point is not to pay TRX commission, but to pay with energy

to make 1 transaction (USDT), approximately 14k of energy is needed, energy can be obtained for a steak (it can be done by hand, by spoiling the private key in TronLink).

and make the automatic energy delegation setting (if there is enough of it on the fee_account). and use it together burning TRX

**Comment by dmytro-samoylenko** [comment]
Hello,

If I understand correctly, TRON allows to [freeze some TRX ](https://developers.tron.network/reference/freezebalancev2-1) to obtain energy and bandwidth (resources needed to make transactions and contract function calls). Additionally, it is possible to [delegate staked TRX to another account](https://developers.tron.network/reference/delegateresource-1). These features could be used to make internal (from one_time to fee_deposit) and external (from fee-deposit) transactions free of TRX burning. Currently we burning 13-27 TRX for each transfer of trc20 token .

Thank you for suggestion. Our team will consider implementation of staking and delegation in next Shkeeper's releases.

**Comment by bulhiCzar** [comment]
also, as an additional(easier way), you can minimize the amount of gas TRX
, you can wait until the amount of gas to be sent from USDT(payment_wallet) to USDT(fee_wallet) will be minimal-average for half a day
so we get the lowest possible payment for commissions

more detailed:
1) we receive USDT on payment_wallet
2) we need to output USDT to fee_wallet
3) we are waiting for the commission to be low (30.000 Energy or 14 TRX)
4) if point 3 is true, then we send it to fee_wallet

pluses:
- the commission will be the lowest possible
cons:
- all our funds will be found on different wallets

recommendation:
add env for payments and withdrawals with different keys
