### ISSUE TITLE
Can't use any @api_key_required endpoints other than payment_request

### ISSUE THREAD

**Issue by petabyt** [vsys-host/shkeeper.io#25]
When I perform the requests with the correct headers, I always get `{"message":"Bad API key","status":"error"}`

**Comment by dmytro-samoylenko** [comment]
Hello,

Please provide shkeeper's image version and full HTTP request/response listings.

**Comment by petabyt** [comment]
> 

I'm on the latest commit from master.
```
$ curl -H "X-Shkeeper-API-Key: XXXXXXX" http://localhost:1240/api/v1/doge/addresses
{"message":"Bad API key","status":"error"}
```

**Comment by petabyt** [comment]
I think it worked when I put in the session id after logging into the web interface. Is it not meant to be used from curl?

**Comment by dmytro-samoylenko** [comment]
Hello,

I can't reproduce the issue. Please make sure your api key matches "API Key:" as displayed at http://localhost:1240/wallet/DOGE
