### ISSUE TITLE
[FEATURE REQUEST] Accept stablecoins

### ISSUE THREAD

**Issue by mrkomarov** [vsys-host/shkeeper.io#3]
My business needs to accept USDT.TRC20 payments. Is it possible to integrate this on _shkeeper_?

**Comment by vsyshost** [comment]
Yes, it's possible! USDT payments are planned to be implemented by SHKeeper in August 2022.

**Comment by vsyshost** [comment]
> My business needs to accept USDT.TRC20 payments. Is it possible to integrate this on _shkeeper_?

Yes, it's possible! USDT payments are planned to be implemented by SHKeeper in August 2022.

**Comment by mrkomarov** [comment]
Hello, is there a deadline for SHKeeper accepting USDT?

**Comment by vsyshost** [comment]
> Hello, is there a deadline for SHKeeper accepting USDT?

We have already released USDT (TRC-20).
Now USDT-TRC20 as a payment option available for paid SHKeeper version.
