### ISSUE TITLE
Suggestion for using Lite full node instead of full node

### ISSUE THREAD

**Issue by Phoenix997733** [vsys-host/shkeeper.io#33]
Is it possible to deploy Lite full node from java-tron instead of full node. It requires way less space and maybe other specs

**Comment by drag0n-flyer** [comment]
#18

**Comment by Phoenix997733** [comment]
Thank you so much for the information. After a lot of trying I was able to deploy Lite full node but none of the backups was accepted except with the date 15052023. Right now it shows me that it's syncing with more than 2 million blocks. The problem is that this number is increasing and I didn't notice it decreasing.
BTW, the ip for downloading the backup was changed since May 2023. Right now it's http://3.219.199.168/

Source: https://developers.tron.network/docs/main-net-database-snapshots
