### ISSUE TITLE
Bug(hot): there is no difference which coin to send

### ISSUE THREAD

**Issue by bulhiCzar** [vsys-host/shkeeper.io#35]
I received 9 USDT. and the notification said 9.00000100

i look for key 'balanceCrypto'

my wallet:
USDT
![изображение](https://github.com/vsys-host/shkeeper.io/assets/70818351/f2d9af02-c1e8-4ea8-9af9-7833fe583359)

TRX
![изображение](https://github.com/vsys-host/shkeeper.io/assets/70818351/50c7493c-8211-4ddf-b76f-72839968a875)

my notification:
`{"fiat": "USD", "paid": true, "crypto": "USDT", "status": "PAID", "externalId": "312", "feePercent": "0", "balanceFiat": "9.00", "overpaidFiat": "0.00", "transactions": [{"date": "2023-08-07 16:49:13", "txid": "72***22", "trigger": false, "amountFiat": "9.00", "amountCrypto": "9.00000000"}, {"date": "2023-08-07 18:11:41", "txid": "93***06", "trigger": true, "amountFiat": "0.00", "amountCrypto": "0.00000100"}], "balanceCrypto": "9.00000100"}`

although tronscan.org does not display this transaction at 0.00000100 for USDT. it was made in TRX

result:  9.00000100 USDT
from:
1)  9.00000000 USDT
2)  0.00000100 TRX

in theory, you can cheat the system by sending 100 TRX instead of 100 USDT

**Comment by bulhiCzar** [comment]
no. its function default disabled (i ckeked)

pls. check this case

**Comment by bulhiCzar** [comment]
i send on support@vsys.host

**Comment by dmytro-samoylenko** [comment]
Hello,

> in theory, you can cheat the system by sending 100 TRX instead of 100 USDT

This only possible if you are using `balanceCrypto` amount from notification. All `*Fiat` fields will show you the right amount.

I can add currency field to each transaction received in notification, e.g.:

```
"transactions": [
    {"date": "2023-08-07 16:49:13", "txid": "72***22", "trigger": false, "amountFiat": "9.00", "amountCrypto": "9.00000000", "crypto": "USDT"},
    {"date": "2023-08-07 18:11:41", "txid": "93***06", "trigger": true, "amountFiat": "0.00", "amountCrypto": "0.00000100", "crypto": "TRX"}
]
```

But not sure what to do with `balanceCrypto`. My guess is to keep it, but only keep track of invoice currency, e.g.:

invoice currency = USDT
transactions: [10 USDT, 100 USDT, 1000 TRX]
balanceCrypto: 110USDT

**Comment by bulhiCzar** [comment]
it's a good idea. I think everyone expected such logic from him
> My guess is to keep it, but only keep track of invoice currency, e.g.:

or add `balanceClear`, which will not take into account TRX and ETH for USDT and USDC

**Comment by bulhiCzar** [comment]
the bug is repeated

it is currently being played, for USDT = USDC

- the payment was in USDT
- the payment was in USDC
- the payment has been confirmed

**Comment by dmytro-samoylenko** [comment]
Hello,

Please explain why you think you encountered a bug? The possibility to pay invoice with multiple currencies is a feature of Shkeeper.

**Comment by bulhiCzar** [comment]
I have generated a payment in USDT.
paid in USDT.
and the payment was marked as "paid".

**Comment by dmytro-samoylenko** [comment]
Hello,

If you have both TRC20 USDC and TRC20 USDT enabled in Shkeeper, the invoice will be marked as Paid if the payment was sent using any of these currencies, given that the payed amount converted to fiat (USD) is enough to settle the invoice.
