### ISSUE TITLE
Tron USDT received tokens appear in transaction but doesn't appear in balance

### ISSUE THREAD

**Issue by Phoenix997733** [vsys-host/shkeeper.io#36]
I want to know if I can do something for this problem and my balance is still zero although I'm receiving money and transactions appears

**Comment by dmytro-samoylenko** [comment]
Hello,

You will not see funds on balance if your Fee-deposit account lacks TRX as these needed to transfer funds from one-time account (to which you received payment) to main account (which used to store funds and make payouts).

**Comment by Phoenix997733** [comment]
Thank you so much for the information. It worked! But the previous transactions didn't appear. Will they appear after some time?

**Comment by dmytro-samoylenko** [comment]
Hello,

They should appear if you have enough ETH on the fee deposit account. The task which checks all accounts and transfers tokens to main account fires every hour or so. You may also check ethereum-shkeeper tasks container logs for any errors.

**Comment by Phoenix997733** [comment]
Thank you so much. Everything worked as intended. But could I ask why there should be sub - wallets and a main wallet? Is it possible to have only one direct wallet for paying to or pay the transactions which is less than some amount to the main wallet directly?
It won't be feasible if someone is paying 10 usdt and I will lose 1 because of the fees.
Maybe if there's a possibility to show sub wallets balance and have the choice to control when to send the balance from them to the main wallet or when it reaches a certain amount. I think this can be good to reduce fees when there's not a lot of payments on this wallet on certain days.

**Comment by dmytro-samoylenko** [comment]
> But could I ask why there should be sub - wallets and a main wallet? Is it possible to have only one direct wallet for paying to or pay the transactions which is less than some amount to the main wallet directly?

When your clients are paying you to the same one wallet it is impossible to automatically determine who paid you. Thats why shkeeper generates new address for each payment.

The overhead of payout when having one main account and multiple one-time accounts it terms of fee is N+1, which is not much.

You may add a fixed amount to the total you present for your client to compensate for a fee.

Decreasing/optimizing transfer fees is a non-goal for our project now.

> Maybe if there's a possibility to show sub wallets balance and have the choice to control when to send the balance from them to the main wallet or when it reaches a certain amount

Actually tron-shkeeper uses  MIN_TRANSFER_THRESHOLD environment variable (0.5 by default) to control transfer from one-time to main account.

**Comment by Phoenix997733** [comment]
I see, Thank you for your time.
Just want to mention a point that it took from trx balance 15 trx for every transaction.
Yes, I think adding a fixed amount from the client side interface will solve the problem.

**Comment by aboozaid** [comment]
> Hello,
> 
> They should appear if you have enough ETH on the fee deposit account. The task which checks all accounts and transfers tokens to main account fires every hour or so. You may also check ethereum-shkeeper tasks container logs for any errors.

Is there any way to override the task timer to be every 15min instead from yaml file?

**Comment by ludmildev** [comment]
> > Hello,
> > They should appear if you have enough ETH on the fee deposit account. The task which checks all accounts and transfers tokens to main account fires every hour or so. You may also check ethereum-shkeeper tasks container logs for any errors.
> 
> Is there any way to override the task timer to be every 15min instead from yaml file? if no please can you tell us how to change it and rebuild helm repo to use the updated code?

You can change it from the values.yaml file under:

tron_shkeeper:
    extraEnv:
        BALANCES_RESCAN_PERIOD: 54000
