### ISSUE TITLE
[SUPPORT REQUEST]

### ISSUE THREAD

**Issue by ProTechEx** [vsys-host/shkeeper.io#4]
Hello,

according your Docu: https://shkeeper.io/kb/start-to-work/documentation-on-launching  
i just tried to install SHkeeper on my local VMWare Ubuntu 20.04

---

root@ubuntu:# curl -sfL https://get.k3s.io | sh -  
\[INFO\]  Finding release for channel stable  
\[INFO\]  Using v1.24.4+k3s1 as release  
\[INFO\]  Downloading hash https://github.com/k3s-io/k3s/releases/download/v1.24.4                                                                                                                                                             +k3s1/sha256sum-amd64.txt  
\[INFO\]  Downloading binary https://github.com/k3s-io/k3s/releases/download/v1.24                                                                                                                                                             .4+k3s1/k3s  
\[INFO\]  Verifying binary download  
\[INFO\]  Installing k3s to /usr/local/bin/k3s  
\[INFO\]  Skipping installation of SELinux RPM  
\[INFO\]  Creating /usr/local/bin/kubectl symlink to k3s  
\[INFO\]  Creating /usr/local/bin/crictl symlink to k3s  
\[INFO\]  Creating /usr/local/bin/ctr symlink to k3s  
\[INFO\]  Creating killall script /usr/local/bin/k3s-killall.sh  
\[INFO\]  Creating uninstall script /usr/local/bin/k3s-uninstall.sh  
\[INFO\]  env: Creating environment file /etc/systemd/system/k3s.service.env  
\[INFO\]  systemd: Creating service file /etc/systemd/system/k3s.service  
\[INFO\]  systemd: Enabling k3s unit  
Created symlink /etc/systemd/system/multi-user.target.wants/k3s.service → /etc/s                                                                                                                                                             ystemd/system/k3s.service.  
\[INFO\]  systemd: Starting k3s  
root@ubuntu:# ln -s /etc/rancher/k3s/k3s.yaml /root/.kube/config  
ln: failed to create symbolic link '/root/.kube/config': No such file or directo                                                                                                                                                             ry  
root@ubuntu:# mkdir -p $HOME/.kube  
root@ubuntu:# ln -s /etc/rancher/k3s/k3s.yaml /root/.kube/config  
root@ubuntu:# curl https://raw.githubusercontent.com/helm/helm/main/scripts/get-helm-3 |                                                                                                                                                     bash  
 % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current  
                                Dload  Upload   Total   Spent    Left  Speed  
100 11156  100 11156    0     0  27613      0 --:--:-- --:--:-- --:--:-- 27545  
Downloading https://get.helm.sh/helm-v3.9.4-linux-amd64.tar.gz  
Verifying checksum... Done.  
Preparing to install helm into /usr/local/bin  
helm installed into /usr/local/bin/helm  
root@ubuntu:# helm repo add vsys-host https://vsys-host.github.io/helm-charts  
"vsys-host" has been added to your repositories  
root@ubuntu:# helm install my-shkeeper vsys-host/shkeeper  
NAME: my-shkeeper  
LAST DEPLOYED: Fri Sep  2 09:11:31 2022  
NAMESPACE: default  
STATUS: deployed  
REVISION: 1  
TEST SUITE: None  
root@ubuntu~:~\# kubectl get pods -n shkeeper  
NAME                                   READY   STATUS              RESTARTS   AGE  
shkeeper-deployment-5f979f46fc-tsfz5   0/1     ContainerCreating   0          27s  
dogecoind-deployment-964cc57c9-hjtxm   0/2     ContainerCreating   0          27s  
litecoind-deployment-d978668f6-b8gx9   0/2     ContainerCreating   0          27s  
bitcoind-deployment-8597459577-vccs4   0/2     ContainerCreating   0          27s

---

**Unfortunately i can't reach the Login Page:**  
Login: http://192.168.202.129:5000/

By the way, i will much better if can provide a installation script for SHKeeper.

And how about securing to GUI with SSL ? Is the are a solution as well ?

**Comment by ProTechEx** [comment]
Is some one here which does reply ? Since 20 days no reply ? Thas realy strange

**Comment by vsyshost** [comment]
> Hello,
> 
> according your Docu: https://shkeeper.io/kb/start-to-work/documentation-on-launching i just tried to install SHkeeper on my local VMWare Ubuntu 20.04
> 
> root@ubuntu:# curl -sfL https://get.k3s.io | sh - [INFO]  Finding release for channel stable [INFO]  Using v1.24.4+k3s1 as release [INFO]  Downloading hash https://github.com/k3s-io/k3s/releases/download/v1.24.4                                                                                                                                                             +k3s1/sha256sum-amd64.txt [INFO]  Downloading binary https://github.com/k3s-io/k3s/releases/download/v1.24                                                                                                                                                             .4+k3s1/k3s [INFO]  Verifying binary download [INFO]  Installing k3s to /usr/local/bin/k3s [INFO]  Skipping installation of SELinux RPM [INFO]  Creating /usr/local/bin/kubectl symlink to k3s [INFO]  Creating /usr/local/bin/crictl symlink to k3s [INFO]  Creating /usr/local/bin/ctr symlink to k3s [INFO]  Creating killall script /usr/local/bin/k3s-killall.sh [INFO]  Creating uninstall script /usr/local/bin/k3s-uninstall.sh [INFO]  env: Creating environment file /etc/systemd/system/k3s.service.env [INFO]  systemd: Creating service file /etc/systemd/system/k3s.service [INFO]  systemd: Enabling k3s unit Created symlink /etc/systemd/system/multi-user.target.wants/k3s.service → /etc/s                                                                                                                                                             ystemd/system/k3s.service. [INFO]  systemd: Starting k3s root@ubuntu:# ln -s /etc/rancher/k3s/k3s.yaml /root/.kube/config ln: failed to create symbolic link '/root/.kube/config': No such file or directo                                                                                                                                                             ry root@ubuntu:# mkdir -p $HOME/.kube root@ubuntu:# ln -s /etc/rancher/k3s/k3s.yaml /root/.kube/config root@ubuntu:# curl https://raw.githubusercontent.com/helm/helm/main/scripts/get-helm-3 |                                                                                                                                                     bash  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current                                 Dload  Upload   Total   Spent    Left  Speed 100 11156  100 11156    0     0  27613      0 --:--:-- --:--:-- --:--:-- 27545 Downloading https://get.helm.sh/helm-v3.9.4-linux-amd64.tar.gz Verifying checksum... Done. Preparing to install helm into /usr/local/bin helm installed into /usr/local/bin/helm root@ubuntu:# helm repo add vsys-host https://vsys-host.github.io/helm-charts "vsys-host" has been added to your repositories root@ubuntu:# helm install my-shkeeper vsys-host/shkeeper NAME: my-shkeeper LAST DEPLOYED: Fri Sep  2 09:11:31 2022 NAMESPACE: default STATUS: deployed REVISION: 1 TEST SUITE: None root@ubuntu~:~# kubectl get pods -n shkeeper NAME                                   READY   STATUS              RESTARTS   AGE shkeeper-deployment-5f979f46fc-tsfz5   0/1     ContainerCreating   0          27s dogecoind-deployment-964cc57c9-hjtxm   0/2     ContainerCreating   0          27s litecoind-deployment-d978668f6-b8gx9   0/2     ContainerCreating   0          27s bitcoind-deployment-8597459577-vccs4   0/2     ContainerCreating   0          27s
> 
> **Unfortunately i can't reach the Login Page:** Login: http://192.168.202.129:5000/
> 
> By the way, i will much better if can provide a installation script for SHKeeper.
> 
> And how about securing to GUI with SSL ? Is the are a solution as well ?

Please accept our apologies for taking so long with the answer. 

Apparently, documentation has a missed step, where you are supposed to create a directory /root/.kube 

We have tested and successfully launched SHKeeper using our Incredible VPS. We have also launched SHKeeper from a VirtualBox with 1 core / 1 Gb RAM.

It is quite possible that you didn't wait till the launching of the container. This practically means you tried to enter when containers were in the creation process. 

Hence, the service should start working only after the command " kubectl get pods -n shkeeper " returns the RUNNING status to all actions. 

---

Yes, there is a solution for SSL. For k3s with Traefik Ingress controller (which is the default for k3s), you can get SSL for your SHKeeper GUI using the detailed instructions over here:
[https://shkeeper.io/kb/use-cases/how-to-use-domain-or-ssl-with-shkeeper](https://shkeeper.io/kb/use-cases/how-to-use-domain-or-ssl-with-shkeeper)
