### ISSUE TITLE
Idea: import/export private key | backup | restore

### ISSUE THREAD

**Issue by bulhiCzar** [vsys-host/shkeeper.io#40]
The private wallet has already been configured to spoil.

I propose to do "Export" of a private switch, also in the UI. this would be useful when moving to another server
After unrolling the new copy, you didn’t have to bother with the remaining amounts on the old copy

**Comment by dmytro-samoylenko** [comment]
Hello,

We already have export button in the manage tab for each crypto. The result is in coin-specific file format. Its ok for a purpose of backing up the keys, but no easy way to import it back. For now it is not a priority to add import key feature. In case you need to make a backup (and you probably should do it from time to time) or move to a new server you can use my backup script:

```
# cat ./backup.sh
#!/bin/bash

dir=/backups/`date +"%F-%T"`
mkdir -p $dir{,/btc,/ltc,/doge,/shkeeper,/tron-shkeeper,/monero-wallet-rpc}/

cp -a /var/lib/rancher/k3s/storage/pvc-*_shkeeper_litecoind-claim/shkeeper "$dir/ltc/"
cp -a /var/lib/rancher/k3s/storage/pvc-*_shkeeper_dogecoind-claim/shkeeper "$dir/doge/"
cp -a /var/lib/rancher/k3s/storage/pvc-*_shkeeper_bitcoind-claim/shkeeper "$dir/btc/"
cp -a /var/lib/rancher/k3s/storage/pvc-*_shkeeper_shkeeper-db-claim/shkeeper.sqlite "$dir/shkeeper/"
cp -a /var/lib/rancher/k3s/storage/pvc-*_shkeeper_tron-shkeeper-data "$dir/tron-shkeeper/"
cp -a /var/lib/rancher/k3s/storage/pvc-*_shkeeper_monero-wallet-rpc/wallet/ "$dir/monero-wallet-rpc/"
```

**Comment by bulhiCzar** [comment]
could you also give a script for restore from backup

**Comment by bulhiCzar** [comment]
`
kubectl -n shkeeper scale --replicas=0 deploy <NAME>
*move file on cerrent dir*
kubectl -n shkeeper scale --replicas=1 deploy <NAME>
`
