### ISSUE TITLE
Helm chart - Secret "password" is missing in shkeeper-btc-key

### ISSUE THREAD

**Issue by MugenTwo** [vsys-host/shkeeper.io#44]
I am getting the following error when I try to deploy using the helm chart:
  Warning  Failed     10s (x3 over 28s)  kubelet            Error: couldn't find key password in Secret shkeeper/shkeeper-btc-key
  
I checked the chart and it doesn't seem to have a "password" key inside of it, however it is being referenced in the deployment of dogecoind.yaml.

![image](https://github.com/vsys-host/shkeeper.io/assets/17546545/a715aa84-471c-4ea6-aa14-417c9088cc89)

And here is the secret shkeeper-btc-key

![image](https://github.com/vsys-host/shkeeper.io/assets/17546545/f412af17-8530-4d63-b7f5-c3b861cb9ac2)

**Comment by ludmildev** [comment]
any fix here, I have the same issue?
