### ISSUE TITLE
[Bug] The output that was not recorded in the database. but it was committed on the blockchain

### ISSUE THREAD

**Issue by bulhiCzar** [vsys-host/shkeeper.io#48]
If we conclude during the "synchronization" that it will take place on the blockchain network. but the page itself will be in an "infinite loading" state. and this entry will not be recorded in the shkeeper database

I came across this on USDT trc 20

**Comment by dmytro-samoylenko** [comment]
Hello,

So, if you make a payout of TRC20 USDT while the wallet showing "synchronization", the payout transaction succeed but no record of it in the Payouts table, correct?

**Comment by bulhiCzar** [comment]
yes

I haven't tested it on other coins, but I think the behavior will be similar

**Comment by bulhiCzar** [comment]
The problem repeats itself

Version: 2.1.36
