### ISSUE TITLE
[Bug] Small balance

### ISSUE THREAD

**Issue by bulhiCzar** [vsys-host/shkeeper.io#49]
issue:
if the amount is withdrawn above the current balance, the transaction is successful. Although there must have been a mistake

coin:
TRC20 USDT

flow:
1. there is 100 USDT on the balance
2. I make a request to withdraw 1000 USDT
3. everything passes successfully, tx hash is issued
4. but the transaction itself in the blockchain failed

**Comment by dmytro-samoylenko** [comment]
Hello,

Fixed in latest version.
