### ISSUE TITLE
helm repo 404

### ISSUE THREAD

**Issue by krama-d** [vsys-host/shkeeper.io#55]
repo is probably dead

https://github.com/vsys-host/shkeeper.io/blob/1e59812524dbc5a2a247aa60d1de61d84171295a/README.md?plain=1#L59

**Comment by yukonet** [comment]
Are you having trouble installing SHKeeper?
We tested and this repo is added without problems when installing the SHKeeper

**Comment by krama-d** [comment]
Yes, when installing on the server, I get a 404 error when adding the repository using the repository documentation.

**Comment by yukonet** [comment]
Repo responds with index.yaml file

Try requesting https://helm.mittwald.de/index.yaml with curl from your server.

**Comment by krama-d** [comment]
cool, please update readme to the latest
