### ISSUE TITLE
Resource consumption question

### ISSUE THREAD

**Issue by aboozaid** [vsys-host/shkeeper.io#61]
First Thank you guys for making such a great project open to public!

I just have some doubts and I want to ask about them hopefully to find answers

* Why do I need to have such a massive VPS resources?
* If I want to host it on a low cost vps, Can I use [publicnode](https://publicnode.com/) RPC for transaction processing?

Thank you again

**Comment by yukonet** [comment]
Hello,

You can find requirements by following link: https://shkeeper.io/#requirements
A lot of resources are needed only if you use your own fullnodes.
In the case of using external fullnodes, the requirements for the server are much smaller.
You can use external fullnodes for  USDT (ERC20, TRC20, BEP-20), USDC (ERC20, TRC20, BEP-20), ETH, TRX, BNB, XRP

**Comment by aboozaid** [comment]
Is your external full nodes provided by you free of charge to use?

**Comment by yukonet** [comment]
Yes, our fullnodes are free to use
