### ISSUE TITLE
Run sandbox instance on the same host

### ISSUE THREAD

**Issue by aboozaid** [vsys-host/shkeeper.io#65]
Hello

Is there a way to change the default port so that I can run multiple instance on the same host? because I cannot use the same port twice.

Thanks for the great work guys!

**Comment by yukonet** [comment]
Hello,
You can deploy a second instance of SHKeeper in the new namespace.
To do this, add the following variables to the values ​​in the shkeeper2-values.yaml file

```
namespace: my-shkeeper2 

shkeeper:
  port: 5002 # any unused port 
```

To deploy a new instance of SHKeeper, run the following command:

`helm install -f shkeeper2-values.yaml my-shkeeper2 vsys-host/shkeeper`

**Comment by aboozaid** [comment]
> Hello, You can deploy a second instance of SHKeeper in the new namespace. To do this, add the following variables to the values ​​in the shkeeper2-values.yaml file
> 
> ```
> namespace: my-shkeeper2 
> 
> shkeeper:
>   port: 5002 # any unused port 
> ```
> 
> To deploy a new instance of SHKeeper, run the following command:
> 
> `helm install -f shkeeper2-values.yaml my-shkeeper2 vsys-host/shkeeper`

Thank you.

Do you have any guide on how can we contribute and where we can push updates?

**Comment by vsyshost** [comment]
You can contribute via GitHub or support on the website. We accept contributions for top 100 blockchain/coin modules and integrations for CMS and frameworks. Other features may be declined at the team's discretion.
