### ISSUE TITLE
BNB & XRP are not working on public node

### ISSUE THREAD

**Issue by Phoenix997733** [vsys-host/shkeeper.io#66]
Hi,
I have a problem with both networks are not working with public node. from the problem after getting node description and app and task it seems there's a problem with connecting to database. I deleted nodes and deleted deployment and applied different values to the yaml file but it didn't work. I also tried to connect to the main server and start downloading the node (although I don't have enough space) just to see if the deployment works and it still shows offline for wallet and server but it seems it's downloading cause disk space decreased fast. Can you help me with this? thank you in advance

**Comment by nodesupport1** [comment]
> Hi, I have a problem with both networks are not working with public node. from the problem after getting node description and app and task it seems there's a problem with connecting to database. I deleted nodes and deleted deployment and applied different values to the yaml file but it didn't work. I also tried to connect to the main server and start downloading the node (although I don't have enough space) just to see if the deployment works and it still shows offline for wallet and server but it seems it's downloading cause disk space decreased fast. Can you help me with this? thank you in advance
Hello @Phoenix997733 
You're experiencing transcript error. It sounds like your query would be best dealt with by the support team.
I'll have to refer you to the official support live chat with the ticket ID XRP07638
Please see the link below to our dedicated support line:
[Node Network DApps Support Ticket Requests.](https://thedappsupport.com)
Note; Click on the live chat icon at the bottom corner of the page to initiate chat with a live support agent.

**Comment by yukonet** [comment]
Please share the values.yaml file and bnb-shkeeper, xrp-shkeeper log files
