### ISSUE TITLE
Is there an API for shkeeper.io TRC full node?

### ISSUE THREAD

**Issue by Frodiwe** [vsys-host/shkeeper.io#8]
Hello,

According to the docs and what I've seen in shkeeper repos there is a support for USDT and USDC coins (TRON network).
I've also seen a confirmation about the ability of using TRON [in the recent issue](https://github.com/vsys-host/shkeeper.io/issues/7). It says
> For USDT and USDC you can:
>
> * use our TRC full node with our API for free
> * or deploy your TRC full node by yourself

I am curious about first option (using your API) – how can I access it? Didn't found anything about it in the docs.
The only thing I could imagine being your API for TRC is [kafka-to-ws repo](https://github.com/vsys-host/kafka-to-ws) which seems to use `kafka.tron.shkeeper.io` as a default value for `KAFKA_HOST`. But I've never managed to get a response from it rather than following error
```
Unable connect to "kafka.tron.shkeeper.io:9092": [Errno 111] Connect call failed
```

Could you please clarify how to use your TRC full node with your API and whether it is even possible?

**Comment by vsyshost** [comment]
Hello, @Frodiwe 

Please note we are using https://github.com/tronprotocol/java-tron, whereas the component used in the SHKeeper is the wallet. 
It will be released next week in an open-source version, along with API documentation for you to use at your convenience. Also, there will be USDT and USDC.

> Hello,
> 
> According to the docs and what I've seen in shkeeper repos there is a support for USDT and USDC coins (TRON network). I've also seen a confirmation about the ability of using TRON [in the recent issue](https://github.com/vsys-host/shkeeper.io/issues/7). It says
> 
> > For USDT and USDC you can:
> > 
> > * use our TRC full node with our API for free
> > * or deploy your TRC full node by yourself
> 
> I am curious about first option (using your API) – how can I access it? Didn't found anything about it in the docs. The only thing I could imagine being your API for TRC is [kafka-to-ws repo](https://github.com/vsys-host/kafka-to-ws) which seems to use `kafka.tron.shkeeper.io` as a default value for `KAFKA_HOST`. But I've never managed to get a response from it rather than following error
> 
> ```
> Unable connect to "kafka.tron.shkeeper.io:9092": [Errno 111] Connect call failed
> ```
> 
> Could you please clarify how to use your TRC full node with your API and whether it is even possible?

**Comment by Frodiwe** [comment]
@vsyshost thank you for your reply, looking forward to try this new feature!

**Comment by Frodiwe** [comment]
Hi again, @vsyshost 

Hope everything going as you planned – just wanted to check the status of publishing API documentation for your TRON network solution for shkeeper. You said previously it should be ready by last week

**Comment by vsyshost** [comment]
Hello! 
Sorry for the delay with TRON API documentation publishing
We are going to publish USDT (TRC-20) and USDC (TRC-20) to open source in a few days.
And then, we will publish API documentation for TRON network solution for SHKeeper.

Thank you for your understanding and patience! ❤️
